from sqlalchemy import *
from migrate import *

from migrate.changeset import schema
#meta = MetaData()
#users = Table('users', meta)
#roles = Table('roles', meta)
#endpoint_templates = Table('endpoint_templates', meta)
#token = Table('token', meta)
#user_roles = Table('user_roles', meta)
#services = Table('services', meta)
#credentials = Table('credentials', meta)
#endpoints = Table('endpoints', meta)
#tenants = Table('tenants', meta)

def upgrade(migrate_engine):
    meta = MetaData(bind=migrate_engine)
    users = Table('users', meta, autoload=True)
    users.rename('users_d5')
    roles = Table('roles', meta, autoload=True)
    roles.rename('roles_d5')
    endpoint_templates = Table('endpoint_templates', meta, autoload=True)
    endpoint_templates.rename('endpoint_templates_d5')
    token = Table('token', meta, autoload=True)
    token.rename('token_d5')
    user_roles = Table('user_roles', meta, autoload=True)
    user_roles.rename('user_roles_d5')
    services = Table('services', meta, autoload=True)
    services.rename('services_d5')
    credentials = Table('credentials', meta, autoload=True)
    credentials.rename('credentials_d5')
    endpoints = Table('endpoints', meta, autoload=True)
    endpoints.rename('endpoints_d5')
    tenants = Table('tenants', meta, autoload=True)
    tenants.rename('tenants_d5')
    
def downgrade(migrate_engine):
    meta = MetaData(bind=migrate_engine)
    users = Table('users_d5', meta, autoload=True)
    users.rename('users')
    roles = Table('roles_d5', meta, autoload=True)
    roles.rename('roles')
    endpoint_templates = Table('endpoint_templates_d5', meta, autoload=True)
    endpoint_templates.rename('endpoint_templates')
    token = Table('token_d5', meta, autoload=True)
    token.rename('token')
    user_roles = Table('user_roles_d5', meta, autoload=True)
    user_roles.rename('user_roles')
    services = Table('services_d5', meta, autoload=True)
    services.rename('services')
    credentials = Table('credentials_d5', meta, autoload=True)
    credentials.rename('credentials')
    endpoints = Table('endpoints_d5', meta, autoload=True)
    endpoints.rename('endpoints')
    tenants = Table('tenants_d5', meta, autoload=True)
    tenants.rename('tenants')

